package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Player;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    int insert(Player record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    Player selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    List<Player> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    int updateByPrimaryKey(Player record);
}