package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.TeamTournament;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TeamTournamentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM_TOURNAMENT
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    int insert(TeamTournament record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM_TOURNAMENT
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    List<TeamTournament> selectAll();
}