package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Team;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    int insert(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    Team selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    List<Team> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    int updateByPrimaryKey(Team record);
}