package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Tournament;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TournamentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TOURNAMENT
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TOURNAMENT
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    int insert(Tournament record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TOURNAMENT
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    Tournament selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TOURNAMENT
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    List<Tournament> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TOURNAMENT
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    int updateByPrimaryKey(Tournament record);
}