package lt.vu.mybatis.model;

public class TeamTournament {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM_TOURNAMENT.TEAMS_ID
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    private Integer teamsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM_TOURNAMENT.TOURNAMENTS_ID
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    private Long tournamentsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM_TOURNAMENT.TEAMS_ID
     *
     * @return the value of PUBLIC.TEAM_TOURNAMENT.TEAMS_ID
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    public Integer getTeamsId() {
        return teamsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM_TOURNAMENT.TEAMS_ID
     *
     * @param teamsId the value for PUBLIC.TEAM_TOURNAMENT.TEAMS_ID
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    public void setTeamsId(Integer teamsId) {
        this.teamsId = teamsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM_TOURNAMENT.TOURNAMENTS_ID
     *
     * @return the value of PUBLIC.TEAM_TOURNAMENT.TOURNAMENTS_ID
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    public Long getTournamentsId() {
        return tournamentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM_TOURNAMENT.TOURNAMENTS_ID
     *
     * @param tournamentsId the value for PUBLIC.TEAM_TOURNAMENT.TOURNAMENTS_ID
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    public void setTournamentsId(Long tournamentsId) {
        this.tournamentsId = tournamentsId;
    }
}