package lt.vu.mybatis.model;

public class Tournament {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TOURNAMENT.ID
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TOURNAMENT.NAME
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TOURNAMENT.ID
     *
     * @return the value of PUBLIC.TOURNAMENT.ID
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TOURNAMENT.ID
     *
     * @param id the value for PUBLIC.TOURNAMENT.ID
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TOURNAMENT.NAME
     *
     * @return the value of PUBLIC.TOURNAMENT.NAME
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TOURNAMENT.NAME
     *
     * @param name the value for PUBLIC.TOURNAMENT.NAME
     *
     * @mbg.generated Mon Apr 08 23:24:08 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }
}